source 'http://ruby.taobao.org'

gem 'dalli'
gem 'sinatra'
gem 'thin'
gem 'activesupport'
gem 'activerecord'
gem 'sinatra-activerecord'
gem 'rack'
gem 'tilt-jbuilder'
gem 'mysql2', '0.3.11'
gem 'rails_config'
gem 'rake'
gem 'fast_trie', git: 'https://github.com/witgo/fast_trie.git', require: 'trie'
gem 'chinese_pinyin'
